[FEATURE] Github statistics ingestion for Golang.
fabric8-analytics/fabric8-analytics-worker pull request #919
Opened 2020-09-30 07:54 UTC by jparsai

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2020-09-30 11:31 UTC, yzainee requested changes

2020-09-30 11:31 UTC, yzainee commented on f8a_worker/workers/graph_importer_new.py
> +        self._strict_assert(arguments.get('name'))
check for github url is missing

2020-09-30 11:31 UTC, yzainee commented on f8a_worker/workers/graph_importer_new.py
> +"""Ingest to graph task."""
will leave it to you if you want to rename or keep it like this

2020-09-30 11:32 UTC, yzainee commented on f8a_worker/workers/init_package_flow_new.py
> +        self._strict_assert(isinstance(arguments.get('name'), str))
check for github url is missing

2020-09-30 11:42 UTC, jparsai commented on f8a_worker/dispatcher/nodes.yml
> +    - name: 'NewGithubDetails'
Yes, 'newPackageFlow' will be called with list of selective sub tasks of the flow needs to be executed.  
`selinon.run_flow_selective('flow_name', [<list of sub tasks of given flow>], node_args,....)`
Will be creating an API in jobs to run selective tasks, github can call the that API

2020-09-30 11:48 UTC, jparsai commented on f8a_worker/workers/init_package_flow_new.py
> +        self._strict_assert(isinstance(arguments.get('name'), str))
For package level analysis we may not have version, even currently we drop version in init_ackage_flow
```
        # get rid of version if scheduled from the core analyses
        arguments.pop('version', None)
        arguments.pop('document_id', None)

```
In we put condition will not be able to proceed.
In ingestion flow (init_analysis_flow) version is required there this condition is must.
Please give your comment, if you still want version to be checked.

2020-09-30 12:01 UTC, jparsai commented on f8a_worker/workers/graph_importer_new.py
> +        package_list = [
For now in data importer existing API is used, we are only ingesting github details having existing schema so it works fine, As suggested description/latest version can be set along with github details, but for it schema changes are required which will take some time to understand, modify and test, once these modifications are done new data importer API can be used which will update description, version, github details etc at once.

2020-10-01 06:52 UTC, yzainee commented on f8a_worker/workers/init_package_flow_new.py
> +        self._strict_assert(isinstance(arguments.get('name'), str))
ok. i got the point. when we start the ingestion part, we will need it

2020-10-01 06:55 UTC, yzainee approved these changes
Changes look fine. Please cross check if we need ingest_to_graph or selective_ingest from data importer

2020-10-05 05:04 UTC, merged